### ISSUE TITLE
NC 28 Support

### ISSUE THREAD

**Issue by kaystrobach** [littleredbutton/cloud_bbb#264]
**Is your feature request related to a problem? Please describe.**

please add NC28 / Hub 7 support

**Describe the solution you'd like**

See above.

**Describe alternatives you've considered**

Staying on NC27

**Additional context**

Thank you #kudos

**Comment by busch1982** [comment]
Hallo,

ich habe Nextcloud  NC28 / Hub 7 mal auf unerem Testserver hochgezogen.
Die BBB Integration 2.5.0 scheint zu fuktionieren.
Zumindest in dem Funktionsumfang wie wir es verwenden scheint alles zu funktionieren.

Man müsste also nur den Hinweis im Nextcloud Store ändern.

vielleicht kan das ja jemand bestätigen.

Gruß

Markus

**Comment by mh33dev** [comment]
Hi,
BBB integration in NC 28.0.1 is working (top menu, creation and modification of conference rooms), but context menu to upload files directly into a conference room isn't available anymore. That's one of the most important features. Same issue in two different installations. 

Best regards

Martin

**Comment by abraxaswd** [comment]
It does work here as well.
Best regards

Thomas

**Comment by kaystrobach** [comment]
sry to bother you @sualko what are your plans, will you accept PRs maybe including the swtich to vue? Thanks a lot.

**Comment by ThibautPlg** [comment]
As @mh33dev noticed, the context menu thing isn't working as the front code changed a lot. The 28 PR isn't containing a fix for this yet as it would require more work than simply increase the version compatibility. 
I'm not sure how we will handle this in a short-term. 
For us, the main need for nc28 is to be able to use the room creation tool and have the NC/BBB Url (to join a room) working. I think @zak39 might address the full picture as soon as he can, but as I said it isn't a small change. 

In a way it would be nice to have a 28 release asap, in the other hand that's a shame to loose a feature. We'll keep you informed :)

**Comment by kaystrobach** [comment]
From my POV, feel free to release, put it in the release notes and mark the version as beta. Makes live easier. Maybe it makes sense to have a roadmap, so that other people can start to help out.

**Comment by kaystrobach** [comment]
thanks a lot.

**Comment by zak39** [comment]
Hi everyone,

The "Send to BBB" button is not present, because, from the Nextcloud 28, the OCA.File API is removed : https://docs.nextcloud.com/server/stable/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#removed-apis

So, we need to study how to implement the [nextcloud-files](https://github.com/nextcloud-libraries/nextcloud-files) library in the project and upgrade it to the version 3.X.X.

**Comment by kaystrobach** [comment]
Upgraded from NC28 to 29 and it works sofar, you need to ignore the warning of the extension for now.
