### ISSUE TITLE
Translations are no longer synced

### ISSUE THREAD

**Issue by nickvergessen** [littleredbutton/cloud_bbb#280]
It seems you took over the repo from sualko.
Now master is "protected" and our `nextcloud-bot` can no longer push the translation updates.
Unless the repo belongs to an organisation and the bot account is an administrator of the org, the master branch should not be protected so the bot can still push translations:

![grafik](https://github.com/littleredbutton/cloud_bbb/assets/213943/2d431b2f-cc18-4a49-a23a-3dac4370befa)

Could you remove the protection?
Otherwise we will stop the translation sync for the app.

**Comment by sualko** [comment]
Thanks Joas for the heads up. I'm still associated with the project and will add the bot as admin. Please close the issue if it is resolved.

**Comment by nickvergessen** [comment]
https://github.com/littleredbutton/cloud_bbb/commit/ba06e7738b428d7dac200970e8c913c2bf78fb97

Worked now
