### ISSUE TITLE
NC 29 support

### ISSUE THREAD

**Issue by agru** [littleredbutton/cloud_bbb#282]
**Is your feature request related to a problem? Please describe.**
Our Nextcloud server is currently running version 28.x and as we would like to upgrade to version 29.x it would be great for this add on to support NC 29.

**Describe the solution you'd like**
Official support for Nextcloud version 29.x

**Comment by 1758w** [comment]
Same for us.
Would be really great.

Thx for answer/feedback!

**Comment by dancesWithCycles** [comment]
Me too. ;-)

**Comment by hermann-san** [comment]
meanwhile you may consider ignoring the warning and still use it with NC29 anyways. Apparently it seems to work.
https://github.com/littleredbutton/cloud_bbb/issues/264#issuecomment-2160462471

**Comment by hermann-san** [comment]
a Beta for NC30 is already out. Maybe it makes sense to continue right with NC30

**Comment by ThibautPlg** [comment]
This is in the works, ready to be merged
https://github.com/littleredbutton/cloud_bbb/pull/285

**Comment by ahcm** [comment]
Ignoring the warning and installing anyways can cause a problem because of incompatible symfony versions, breaking occ completly.
In that case move the apps/bbb e.g. to apps/bbb.bak. Then occ app:disable bbb and move it back.

**Comment by ThibautPlg** [comment]
The 2.7.0 release has a problem (see #287 ). Until the next release, we unfortunately have to downgrade. This is not due to the manual version override, as it also breaks nc28.

**Comment by Fuseteam** [comment]
wait so is this supported on nextcloud 29 now?

**Comment by ThibautPlg** [comment]
I'm not sure why the latest release didn't include the version bump. It should works if you force it on your NC server side.
However, we're about to "close the deal" regarding our team finally taking over the app and being able to compile and release by ourselves. So expect a smoother release cycle in the near future.

**Comment by MarcelCoding** [comment]
Has anyone tested 2.7.2 with v30? Is it safe to upgrade? In the metadata, the version is still on v28, but I've been running it successfully on v29 since a long time.

**Comment by R053NR07** [comment]
Is there any Update on this topic? NC28 is almost end-of-life.

**Comment by dasJ** [comment]
NC 28 will go EOL in pretty much one month. Any plans to actually release #307?

**Comment by ThibautPlg** [comment]
Support added up to NC30. We're closing the issue. Thanks all for your patience!
