### ISSUE TITLE
2.7.0 problem with OCC

### ISSUE THREAD

**Issue by ThibautPlg** [littleredbutton/cloud_bbb#287]
Hello,

We're currently facing an issue with the cloud_bbb release 2.7.0. The build distributed through the appstore hasn't been properly builded. 
This is causing issues with any OCC commands run after the upgrade/installation. 

> [!CAUTION]
> **Do not upgrade**

EDIT: The faulty release has been removed from the appstore. This issue can still benefit users, I will unpin and close when the future version is released. 

## 1. Disable 2.7.0
- Use the web interface

or 

- `UPDATE oc_appconfig SET configvalue = 'no' WHERE appid = 'bbb' AND configkey = 'enabled';`

## 2. Downgrade to bbb 2.6.0 or install the patched version

Remove bad 2.7.0
```
rm -rf /var/www/html/nextcloud/apps/bbb/
```
Get the new archive
- 2.6.0 (downgrade): https://github.com/littleredbutton/cloud_bbb/releases/download/v2.6.0/bbb-v2.6.0.tar.gz
- 2.7.0 (patched): https://github.com/littleredbutton/cloud_bbb/releases/download/v2.7.0/cloud_bbb-2.7.0-fixed.tar.gz
- 
```
cd /tmp


# 2.6.0
wget  https://github.com/littleredbutton/cloud_bbb/releases/download/v2.6.0/bbb-v2.6.0.tar.gz

# OR 

# 2.7.0-patched
wget https://github.com/littleredbutton/cloud_bbb/releases/download/v2.7.0/cloud_bbb-2.7.0-fixed.tar.gz

cd /var/www/html/nextcloud/apps
```
```
tar -xvf /tmp/bbb-v2.6.0.tar.gz

# OR

tar -xvf /tmp/cloud_bbb-2.7.0-fixed.tar.gz
```
Adjust permissions (Update webserver username)
```
chown -R nginx: bbb/
find bbb/ -type d -exec chmod 750 {} \;
find bbb/ -type f -exec chmod 640 {} \;
```
Enable the app
```
sudo -u nginx php /var/www/html/nextcloud/occ app:enable bbb
```
----

We're currently discussing the issue with the main maintainer and will publish a new version asap.

**Comment by sualko** [comment]
Sorry everyone. Somehow the build script did not work. I will release a new version asap.
