### ISSUE TITLE
Expose the app version to the capabilities endpoint

### ISSUE THREAD

**Issue by ThibautPlg** [littleredbutton/cloud_bbb#288]
Hello,
Could it be possible to expose the app version through the capabilities endpoint?
This is useful when managing multiple Nextcloud to monitor and report the app version. Many other Nextcloud Apps are already exposing this data (circles, richdocuments, deck to name a few)

Example:
```
curl --request GET \
  --url https://user:password@mycloud.localnet.com/ocs/v2.php/cloud/capabilities \
  --header 'OCS-APIRequest: true'
```
would return 
```
        "bbb": {
          "appVersion": "2.7.0"
        },
```

See : https://github.com/nextcloud/groupfolders/pull/2861/files

Best regards,

**Comment by sualko** [comment]
@ThibautPlg can you create a pull request for this feature?

**Comment by ThibautPlg** [comment]
I haven't developed it, it's only a feature request at the moment.
