### ISSUE TITLE
Release list on apps.nextcloud.com is empty

### ISSUE THREAD

**Issue by znerol** [littleredbutton/cloud_bbb#291]
**Describe the bug**

The release list on apps.nextcloud.com is completely empty. As a result, it is currently impossible to install the app via `occ`.

https://apps.nextcloud.com/apps/bbb/releases

![image](https://github.com/user-attachments/assets/7dec7623-dbc3-4b1a-b0e6-4e9f74b16884)

**To Reproduce**
1. `php occ app:install bbb`

**Expected behavior**

BBB app is installed.

**Actual behavior**

```
Error: Could not download app bbb
```

**Comment by ThibautPlg** [comment]
Hello
This is problematic. We just changed ownership to finish the app takeover, that might be a side effect that we did not know about. 
I'll get in touch with the team. 
Thanks for your report,

**Comment by zak39** [comment]
Hi @znerol 

I fix it, this issue is done.
